server:
    port: 8090
spring:
    kafka:
        consumer:
            bootstrap-servers: localhost:9092
            group-id: 'email'
            auto-offset-reset: earliest
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    mail:
        host: smtp.gmail.com
        port: 587
        username: ${MAIL_USERNAME}
        password: ${MAIL_PASSWORD}
        properties:
            mail:
                smtp:
                    auth: true
                    starttls.enable: true
    devtools:
        livereload:
            enabled: false